### PR TITLE
No more overflow on screen at dialog.dart.

### PR DESCRIPTION
**Pull request by itsarvinddev**
Now you can Playing game on Android with full screen mode(Hide Status bar & Navigation bar).

### CODE REVIEW

**Comment by tsinis** [comment]
Hey @rvndsngwn!

Thank you very much for your PR. I took a quick look at the changes and that's what I think:
1) I haven't checked the Android version on small devices, but if the results window requires scrolling then, instead of wrapping Column with a SingleChildScroll interview you can set scrollable parameter of dialogbox to true (instead of _about):
https://github.com/tsinis/plan_et_b/blob/4ce29b4df01c1238b617dd8b8868fb7c3c7a098b/lib/widgets/dialog.dart#L19

2) I'd like to leave the bar status as a semi-transparent overlay. Still, it's like an indie game, there's no need to be too mediated during the game, I belive :)

I can test the game on my smartphone and debug these flaws, but basically it's mostly a PWA game, I didn't even expect anyone to run it on Android. Thank you again!

**Comment by itsarvinddev** [comment]
Thanks for your response dear @tsinis.

**Comment by tsinis** [comment]
> Thanks for your response dear @tsinis.

Hey @rvndsngwn  thank you for the PR and clarifying the problem. Yesterday I've commited update and added new Releases. The only thing I did change - I didn't hide the status of the bar and just make it transparent (i.e. you will see the time, signal etc.). I hope that you will be satisfied with such a compromise. I have fixed the rest, as I described the comments еаrlier! Thanks again!

**Comment by itsarvinddev** [comment]
Hi, @tsinis, Of course, I checked the new updates, I liked new releases. Your work is great. Thank you very much for your response.

**Pull request closed without merging**
